# These are supported funding model platforms
custom: ["https://github.com/sponsors/BiancoRoyal", https://bianco-royal.space/supporter/", "https://opencollective.com/node-red-contrib-modbus", "https://noderedplus.de/"]
