verbose: false
instrumentation:
    globals: ['expect']
    root: ./src
    default-excludes: true
    excludes: ['src/icons']
    include-all-sources: true
    include-pid: false
    es-modules: true
    ignoreLeaks: false
    ui: bdd
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
reporting:
    print: both
    reports:
        - lcov
        - html
        - cobertura
        - clover
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
