# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Generate Summary"

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
          - 18
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run summary
      - run: echo Test results for NodeJS version ${{ matrix.node-version }} >> $GITHUB_STEP_SUMMARY
      - run: cat summary.md >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v3
        with:
          name: badges
          path: badges
  badgeUpdate:
    name: "Update badges"
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: badges
          path: badges
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - run: git add badges
      - run: git commit -m "Automatically update coverage badges"
      - run: git push --force
